### PR TITLE
improve show hosts  from chaos test

### PR DESCRIPTION
**Pull request by panda-sheep**
As title.
 
The result is as follows:
1) When there is no space
image

2）When the following statement is executed,
```
create space YY;
create space NBA;
```

image

### CODE REVIEW

**Comment by Shylock-Hg** [comment]
What's the issue?

**Comment by panda-sheep** [comment]
> What's the issue?

Unable to display `total`  row and order

**Review by liuyu85cn — APPROVED** [review]
LGTM

**Review by critical27 — APPROVED** [review]
Good job

**Pull request merged**
