### PR TITLE
Correct the latency histogram factor.

### PR DESCRIPTION
**Pull request by Shylock-Hg**

### CODE REVIEW

**Review by yixinglu — COMMENTED** [review]
Why the min value of histogram is set to 2000?

**Comment by Shylock-Hg** [comment]
> Why the min value of histogram is set to 2000?

I don't the latency will less than 2000us.

**Comment by dutor** [comment]
> > Why the min value of histogram is set to 2000?
> 
> I don't think the latency will less than 2000us.

It definitely will.

suggestion: 100000(buckets), 0(ming), 10000000(max)

**Comment by dutor** [comment]
> > > Why the min value of histogram is set to 2000?
> > 
> > 
> > I don't think the latency will less than 2000us.
> 
> It definitely will.
> 
> suggestion: 100000(buckets), 0(ming), 10000000(max)

If concerning the memory consumption, they could be set to 50000, 0, 5000000

**Comment by Shylock-Hg** [comment]
> > > Why the min value of histogram is set to 2000?
> > 
> > 
> > I don't think the latency will less than 2000us.
> 
> It definitely will.
> 
> suggestion: 100000(buckets), 0(ming), 10000000(max)

Set to these.

**Comment by laura-ding** [comment]
> > > > Why the min value of histogram is set to 2000?
> > > 
> > > 
> > > I don't think the latency will less than 2000us.
> > 
> > 
> > It definitely will.
> > suggestion: 100000(buckets), 0(ming), 10000000(max)
> 
> If concerning the memory consumption, they could be set to 50000, 0, 5000000

It is better to enables it to let the user configure?

**Pull request closed without merging**
