### PR TITLE
Remove the meaningless validator to report error.

### PR DESCRIPTION
**Pull request by Shylock-Hg**

### CODE REVIEW

**Review by CPWstatic — COMMENTED** [review]
Why remove it?

**Comment by Shylock-Hg** [comment]
> Why remove it?

Do we need it? When this happened fatal maybe better.

**Comment by CPWstatic** [comment]
> > Why remove it?
> 
> Do we need it? When this happened fatal maybe better.

Prefer removing the DLOGs, and report error for unimplemented statements. For we have considered that we might not provide all implementation for the community.

**Comment by Shylock-Hg** [comment]
> > > Why remove it?
> > 
> > 
> > Do we need it? When this happened fatal maybe better.
> 
> Prefer removing the DLOGs, and report error for unimplemented statements. For we have considered that we might not provide all implementation for the community.

Ok.

**Pull request closed without merging**
