### PR TITLE
storege profile detail

### PR DESCRIPTION
**Pull request by cangfengzhs**
image

### CODE REVIEW

**Comment by cangfengzhs** [comment]
common: https://github.com/vesoft-inc/nebula-common/pull/604

**Comment by cangfengzhs** [comment]
storage: https://github.com/vesoft-inc/nebula-storage/pull/542

**Comment by critical27** [comment]
Would you add a screenshot here?

**Comment by cangfengzhs** [comment]
Has been merged into nebula repo.

**Pull request closed without merging**
