### PR TITLE
Delete tag

### PR DESCRIPTION
**Pull request by critical27**
https://github.com/vesoft-inc/nebula-storage/pull/541
https://github.com/vesoft-inc/nebula-common/pull/603

Supported syntax:
```
# single tag
DELETE TAG t1 FROM "a";
# multiple tag
DELETE TAG t1,t2 FROM"a" ;
# all tag
DELETE TAG * FROM "a";

# delete multiple vertices's tag 
DELETE TAG t1 FROM "a", "b";
```

Pipe and var is supported as well.

### CODE REVIEW

**Comment by Shylock-Hg** [comment]
> [vesoft-inc/nebula-storage#541](https://github.com/vesoft-inc/nebula-storage/pull/541)
> [vesoft-inc/nebula-common#603](https://github.com/vesoft-inc/nebula-common/pull/603)
> 
> Supported syntax:
> 
> ```
> # single tag
> DELETE TAG "a" t1;
> # multiple tag
> DELETE TAG "a" t1,t2;
> # all tag
> DELETE TAG "a" *;
> 
> # delete multiple vertices's tag 
> DELETE TAG "a", "b" t1;
> ```
> 
> Pipe and var is supported as well.

Prefer `delete tag <tag_list> from <vertices>` syntax.

**Comment by critical27** [comment]
> Prefer `delete tag <tag_list> from <vertices>` syntax.

Maybe yours is better. @whitewum which syntax do you prefer?

**Comment by whitewum** [comment]
> > Prefer `delete tag <tag_list> from <vertices>` syntax.
> 
> Yeah, maybe yours is better. @whitewum which syntax do you prefer?

Great!

Cypher using `REMOVE n:Lable` . So `REMOVE` sounds better than `DELETE` for user convience.

**Comment by critical27** [comment]
> > > Prefer `delete tag <tag_list> from <vertices>` syntax.
> > 
> > 
> > Yeah, maybe yours is better. @whitewum which syntax do you prefer?
> 
> Great!
> 
> Cypher using `REMOVE n:Lable` . So `REMOVE` sounds better than `DELETE` for user convience.

REMOVE TAG t1 from "abc"?

**Comment by whitewum** [comment]
> > > > Prefer `delete tag <tag_list> from <vertices>` syntax.
> > > 
> > > 
> > > Yeah, maybe yours is better. @whitewum which syntax do you prefer?
> > 
> > 
> > Great!
> > Cypher using `REMOVE n:Lable` . So `REMOVE` sounds better than `DELETE` for user convience.
> 
> REMOVE TAG t1 from "abc"?

Either syntax is OK.

**Review by bright-starry-sky — APPROVED** [review]
LGTM

**Review by panda-sheep — APPROVED** [review]
Excellent！

**Pull request closed without merging**
