### PR TITLE
fix logo url

### PR DESCRIPTION
**Pull request by HarrisChu**
as title

### CODE REVIEW

**Comment by Shylock-Hg** [comment]
Better add logo to master branch.

**Comment by HarrisChu** [comment]
> Better add logo to OSS

agreed, just keep consistent with https://github.com/vesoft-inc/nebula/pull/2489

**Review by Shylock-Hg — APPROVED** [review]

**Comment by wey-gu** [comment]
Let's merge this ASAP :-)
@randomJoe211

**Comment by jackwener** [comment]
Closes #10

**Comment by HarrisChu** [comment]
fixed by https://github.com/vesoft-inc/nebula-graph/pull/1349

**Pull request closed without merging**
