### PR TITLE
make findvisitor suitable for more scenarios

### PR DESCRIPTION
**Pull request by nevermore3**
for example
go N steps from <vid> over <e> yield e._dst limit[1, 2, 3]
Check if there is a non-integer in the limit list OR check if the value of list is Less than N
There is no targets

### CODE REVIEW

**Comment by czpmango** [comment]
IMO, `FindVisitor` is abstracted to search from a set of targets, and returns true if a target is found. It is not appropriate to modify its original abstract intention just because of its different usage.

In your above scenario, you can do as following:
```
auto finder = [N](const Expression* expr, const std::unordered_set<Value::Type>& targets) -> bool {
    if (expr->kind() == Expression::Kind::kConstant) {
        auto val = static_cast<ConstantExpression>(expr)->value();
        if (targets.find(val.type()) != targets.end() || val > N) {
            return true;
        }
    }
    return false;
};
FindVisitor<Value::Type> visitor(finder, {Value::Type::INT});
const_cast<Expression*>(self)->accept(&visitor);
auto res = visitor.results();
```

**Comment by nevermore3** [comment]
> IMO, `FindVisitor` is abstracted to search from a set of targets, and returns true if a target is found. It is not appropriate to modify its original abstract intention just because of its different usage.
> 
> In your above scenario, you can do as following:
> 
> ```
> auto finder = [N](const Expression* expr, const std::unordered_set<Value::Type>& targets) -> bool {
>     if (expr->kind() == Expression::Kind::kConstant) {
>         auto val = static_cast<ConstantExpression>(expr)->value();
>         if (targets.find(val.type()) != targets.end() || val > N) {
>             return true;
>         }
>     }
>     return false;
> };
> FindVisitor<Value::Type> visitor(finder, {Value::Type::INT});
> const_cast<Expression*>(self)->accept(&visitor);
> if (visitor.found()) {
>     return Status::Error("Invalid limit params.");
> }
> ```

this is a solution,  findVisitor can be used as a basic traversal,  variables can be solved by using lambda capture，no need to use member variables

**Review by czpmango — APPROVED** [review]
Good job. 
This is a better abstraction for `findVisitor`.

**Comment by czpmango** [comment]
Good job. 
This is a better abstraction for `findVisitor`.

> > IMO, `FindVisitor` is abstracted to search from a set of targets, and returns true if a target is found. It is not appropriate to modify its original abstract intention just because of its different usage.
> > In your above scenario, you can do as following:
> > ```
> > auto finder = [N](const Expression* expr, const std::unordered_set<Value::Type>& targets) -> bool {
> >     if (expr->kind() == Expression::Kind::kConstant) {
> >         auto val = static_cast<ConstantExpression>(expr)->value();
> >         if (targets.find(val.type()) != targets.end() || val > N) {
> >             return true;
> >         }
> >     }
> >     return false;
> > };
> > FindVisitor<Value::Type> visitor(finder, {Value::Type::INT});
> > const_cast<Expression*>(self)->accept(&visitor);
> > if (visitor.found()) {
> >     return Status::Error("Invalid limit params.");
> > }
> > ```
> 
> this is a solution, But findVisitor can be used as a basic traversal, variables can be solved by using lambda capture，no need to use member variables

ACK.

**Review by yixinglu — APPROVED** [review]

**Pull request merged**
