### PR TITLE
Let fetch prop on tag return VERTEX

### PR DESCRIPTION
**Pull request by jievince**
Make ` FETCH PRP ON`(without yield) return `Vertex`.
https://jira.nebula-graph.io/browse/NG-388
https://jira.nebula-graph.io/browse/NG-380

### CODE REVIEW

**Comment by Shylock-Hg** [comment]
> Make ` FETCH PRP ON`(without yield) return `Vertex`.
> https://jira.nebula-graph.io/browse/NG-388
> https://jira.nebula-graph.io/browse/NG-380

For the second issue , do we get agreed?

**Comment by Shylock-Hg** [comment]
In this way `fetch prop on * vids yield tag_prop_list`, in this way how can I know the tag_prop_list?

**Comment by jievince** [comment]
> > Make ` FETCH PRP ON`(without yield) return `Vertex`.
> > https://jira.nebula-graph.io/browse/NG-388
> > https://jira.nebula-graph.io/browse/NG-380
> 
> For the second issue , do we get agreed?

We don't get agreed. We might need to have a further discussion and sort out the grammar here

**Comment by jievince** [comment]
> For sentence `fetch prop on * vids yield tag_prop_list`, in this way how can I know the tag_prop_list?

The processing logic of `Fetch prop on with yield ` is the same as before.
image

**Comment by Shylock-Hg** [comment]
> > For sentence `fetch prop on * vids yield tag_prop_list`, in this way how can I know the tag_prop_list?
> 
> The processing logic of `Fetch prop on with yield ` is the same as before.
> image

I mean that user need manually list all tag and properties.

**Comment by jievince** [comment]
> > > For sentence `fetch prop on * vids yield tag_prop_list`, in this way how can I know the tag_prop_list?
> > 
> > 
> > The processing logic of `Fetch prop on with yield ` is the same as before.
> > image
> 
> I mean that user need manually list all tag and properties.
You can use fetch prop without yield, the returned vertices will show all tags and all props

**Review by nevermore3 — APPROVED** [review]

**Review by yixinglu — APPROVED** [review]

**Pull request merged**
