### PR TITLE
Select the tag index by key length.

### PR DESCRIPTION
**Pull request by Shylock-Hg**
Require https://github.com/vesoft-inc/nebula-common/pull/378

### CODE REVIEW

**Comment by bright-starry-sky** [comment]
I don't think this is the right way to handle it. I think choosing an optimal index is based on where conditions, not fields size. 
Of course, we can sort the indices and then make a choice. 
Is a BUG in your PR . for example :
```
tag1 (col1 string)
index1 on tag (col1(2))
index2 on tag (col1(5))
where col1 == "AA" , --> The index1 will be hit. The choice is correct
where col1 == "AAAAA" -->The index1 will be hit too. The choice is wrong. index2 is expected.
```

WDYT?

**Comment by Shylock-Hg** [comment]
> I don't think this is the right way to handle it. I think choosing an optimal index is based on where conditions, not fields size.
> Of course, we can sort the indices and then make a choice.
> Is a BUG in your PR ? for example :
> 
> ```
> tag1 (col1 string)
> index1 on tag (col1(2))
> index2 on tag (col1(5))
> where col1 == "AA" , --> The index1 will be hit. The choice is correct
> where col1 == "AAAAA" -->The index1 will be hit too. The choice is wrong. index2 is expected.
> ```
> 
> WDYT?

No filter if we seek by index itself as the start of match.

**Comment by bright-starry-sky** [comment]
> > I don't think this is the right way to handle it. I think choosing an optimal index is based on where conditions, not fields size.
> > Of course, we can sort the indices and then make a choice.
> > Is a BUG in your PR ? for example :
> > ```
> > tag1 (col1 string)
> > index1 on tag (col1(2))
> > index2 on tag (col1(5))
> > where col1 == "AA" , --> The index1 will be hit. The choice is correct
> > where col1 == "AAAAA" -->The index1 will be hit too. The choice is wrong. index2 is expected.
> > ```
> > 
> > 
> > WDYT?
> 
> No filter if we seek by index itself as the start of match.

Yes, I know. I means LOOKUP and MATCH should have the same processing logic, don't do it this way, otherwise it will be more cluttered.
And the processing logic, I suggest you look at` count (vertices)` by tag.

**Comment by Shylock-Hg** [comment]
Stale

**Pull request closed without merging**
